baseurl = "https://paperwhy.aerobatic.io/"
languageCode = "en-gb"
title = "Paperwhy"
# Enable comments by entering a Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering a tracking code
googleAnalytics = ""
theme = ""
preserveTaxonomyNames = true
enableGitInfo = true
FootnoteReturnLinkContents = "<sup>⇧</sup>"

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
        gitRepository = "//bitbucket.org/mdbenito/paperwhy"
	name = "Paperwhy"
	description = "Paperwhy: your (ir)regular source of paper digests."
	copyright = "Built with [HUGO](//gohugo.io) based on [hikari](//github.com/digitalcraftsman/hugo-hikari-theme) - © 2017 the authors"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "This is PaperWhy. Our sisyphean endeavour not to drown in the immense Machine Learning literature."
	intro = "With thousands of papers every month, keeping up with and making sense of recent research in machine learning has become almost impossible. By routinely reviewing and reporting papers we help ourselves and hopefully someone else."

	# Enable Google search
	search_enabled = true

[[params.authors]]
        name = "Álvaro Tejero Cantero"
	url = "//scholar.google.com/citations?user=VObPwpUAAAAJ&hl=en"
        icon_class = "alvaro"

[[params.authors]]
        name = "Miguel de Benito Delgado"
        url = "//mdbenito.aerobatic.io"
        icon_class = "miguel"

[taxonomies]
        tag = "tags"
        paper_author = "paper_authors"
        author = "authors"
                